# FRIDER配置文件
# 可在程序「设置」页修改；保存后自动生效

root_command = "fk"
frida_server_path = "/data/local/tmp/aj"
frida_client_path = "C:\\Users\\shaoxinSEC\\Desktop\\frider\\frida-16.5.7\\Scripts\\frida.exe"
frida_tools_dir = "C:\\Users\\shaoxinSEC\\Desktop\\frider\\frida-16.5.7\\Scripts"
# frida-ps固定为 -a -i，连接方式见frida_connection
frida_connection = "usb"
frida_remote_host = "127.0.0.1"
frida_remote_port = "99999"
adb_path = "adb"
scrcpy_path = "scrcpy"
scripts_dir = "scripts"
default_proxy = ""
